modLoader="javafml"
loaderVersion="[47,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="create_integrated_farming.mixins.json"

[[mixins]]
config="create_integrated_farming.createenchantablemachinery.mixins.json"

[[mixins]]
config="create_integrated_farming.delightoflight.mixins.json"

[[mixins]]
config="create_integrated_farming.netherdepthsupgrade.mixins.json"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[47.4.10,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
mandatory=true
versionRange="[6.0.8,)"
ordering="AFTER"
side="BOTH"
